# Generated by Django 4.0.5 on 2022-07-03 09:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('fbr_api', '0002_alter_user_email_alter_user_phone_no'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegisterUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cnic', models.CharField(max_length=13, unique=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='fbr',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fbr_api.registeruser'),
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
