# Generated by Django 4.0.5 on 2022-07-03 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fbr_api', '0003_registeruser_alter_fbr_user_delete_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='fbr',
            name='is_seen',
            field=models.BooleanField(default=True),
        ),
    ]
