# Generated by Django 4.0.5 on 2022-07-14 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fbr_api', '0004_fbr_is_seen'),
    ]

    operations = [
        migrations.AddField(
            model_name='fbr',
            name='datetime',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='fbr',
            name='district',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='fbr',
            name='location',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='fbr',
            name='mobile_number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fbr',
            name='police_station',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
