# Generated by Django 4.0.5 on 2022-07-14 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fbr_api', '0005_fbr_datetime_fbr_district_fbr_location_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fbr',
            name='catagory',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='fbr',
            name='datetime',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
